# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uCrewProjectUploader/plugins/ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(320, 235)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(320, 235))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("uCrewProjectUploader/plugins\\../resources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblUcrew = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblUcrew.setFont(font)
        self.lblUcrew.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUcrew.setObjectName("lblUcrew")
        self.verticalLayout_3.addWidget(self.lblUcrew)
        self.lblServer = QtWidgets.QLabel(self.centralwidget)
        self.lblServer.setObjectName("lblServer")
        self.verticalLayout_3.addWidget(self.lblServer)
        self.txtServer = QtWidgets.QLineEdit(self.centralwidget)
        self.txtServer.setObjectName("txtServer")
        self.verticalLayout_3.addWidget(self.txtServer)
        self.lblLogin = QtWidgets.QLabel(self.centralwidget)
        self.lblLogin.setObjectName("lblLogin")
        self.verticalLayout_3.addWidget(self.lblLogin)
        self.txtLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.txtLogin.setObjectName("txtLogin")
        self.verticalLayout_3.addWidget(self.txtLogin)
        self.lblPassword = QtWidgets.QLabel(self.centralwidget)
        self.lblPassword.setObjectName("lblPassword")
        self.verticalLayout_3.addWidget(self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.verticalLayout_3.addWidget(self.txtPassword)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 6, -1, -1)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.btnAuth = QtWidgets.QPushButton(self.centralwidget)
        self.btnAuth.setObjectName("btnAuth")
        self.gridLayout.addWidget(self.btnAuth, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "uCrew - Авторизация"))
        self.lblUcrew.setText(_translate("MainWindow", "uCrew - Авторизация"))
        self.lblServer.setText(_translate("MainWindow", "Сервер:"))
        self.txtServer.setText(_translate("MainWindow", "94.51.83.132"))
        self.lblLogin.setText(_translate("MainWindow", "E-mail / Ф.И.О. / Телефон:"))
        self.lblPassword.setText(_translate("MainWindow", "Пароль:"))
        self.btnAuth.setText(_translate("MainWindow", "Авторизация"))
